
skillMetadata:
  sections:
    - name: OBS BB API
      fields:
        - name: api_host
          type: text
          label: API Host Address
          value: ""
          placeholder: "localhost"
        - name: api_port
          type: text
          label: API Host Port
          value: ""
          placeholder: "5000"
